spring:
  config:
    import: security-variables.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inongram
    username: root
    password: ${mysql.password}
  thymeleaf:
    cache: false
  application:
    name: Inongram
mybatis:
  mapper-locations: mappers/*Mapper.xml